explicit

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -11,10 +11,14 @@ env:
   DEPS: libgmp-dev libmpfr-dev libqd-dev libtool autoconf python3-pip python3-dev python3-flake8
 
 jobs:
-  linux:
+  python3:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Setup Python
+        uses: actions/setup-python@v2
+        with:
+             python-version: '3.x'        
       - name: Check out
         uses: actions/checkout@v2
       - name: Install prerequisites
@@ -23,11 +27,31 @@ jobs:
           sudo DEBIAN_FRONTEND=noninteractive apt-get install $DEPS
       - name: Dependencies
         run: |
-          ./install-dependencies.sh
-          pip3 install Cython
-          pip3 install -r requirements.txt          
+          git clone https://github.com/fplll/fplll
+          cd fplll || exit
+          ./autogen.sh
+          ./configure --disable-static --with-max-enum-dim=64 --with-max-parallel-enum-dim=20
+          make clean
+          make -j $JOBS
+          make install
+          cd ..
+
+          git clone https://github.com/fplll/fpylll
+          cd fpylll || exit
+          pip install Cython
+          pip install -r requirements.txt
+          pip install -r suggestions.txt
+          python setup.py clean
+          python setup.py build_ext
+          python setup.py install
+          cd ..
+
+          # Otherwise py.test may fail
+          rm -rf ./fplll
+          rm -rf ./fpylll
+
       - name: Compile
-        run: python setup.py build_ext --inplace
+        run: python setup.py build_ext -j $JOBS --inplace
 
       - name: Test
-        run: LD_LIBRARY_PATH="$VIRTUAL_ENV/lib" python -m pytest
+        run: python -m pytest
